---

extends: default

rules:
  braces:
    level: warning
    max-spaces-inside: 1
  brackets:
    level: warning
    max-spaces-inside: 1
  colons:
    level: warning
  commas:
    level: warning
  comments: disable
  comments-indentation: disable
  document-start: disable
  hyphens:
    level: warning
  indentation: disable
  line-length: disable
  new-lines: disable
  empty-lines: disable
  truthy: disable
