---

namespace: buluma
name: test_resource_do_not_use
version: 2.5.0
readme: README.md
authors:
  - Michael Buluma (@buluma) <dev@buluma.me.ke>
description: This is a test collection used for running tests on https://github.com/buluma/ansible_galaxy_collection.
license_file: LICENSE
tags: []
repository: https://github.com/buluma/ansible_galaxy_collection
documentation: https://github.com/buluma/ansible_galaxy_collection
issues: https://github.com/buluma/ansible_galaxy_collection/issues
