name: Testing the Action

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  # push:
  #  branches:
  #    - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  RUNNER_TEMP: /tmp
  TEST_ARTIFACT_VERSION: 2.6.1

jobs:
  local_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.3.0
        with:
          node-version: '16.x'

      - name: Use Cache
        uses: actions/cache@v2.1.6
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        run: |
          npm install -g npm
          npm ci
      - name: Check Format
        run: npm run format-check

      - name: Run tests
        run: npm test

  # test_deploy:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2.3.4

  #     - name: Test the action
  #       uses: ./
  #       with:
  #         api_key: '${{ secrets.GALAXY_API_KEY }}'
  #         # Fake location that's a small amount of content
  #         collection_dir: 'fake_collection'

  #     - name: Test the action with a custom version
  #       uses: ./
  #       with:
  #         api_key: '${{ secrets.GALAXY_API_KEY }}'
  #         collection_dir: 'fake_collection'
  #         # Custom version
  #         galaxy_version: '${{ env.TEST_ARTIFACT_VERSION }}-test'

  test_build_then_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      # - name: Test the action - only build
       # uses: ./
       # with:
       #   api_key: '${{ secrets.GALAXY_API_KEY }}'
       #   collection_dir: 'fake_collection'
          # Different from above version
       #   galaxy_version: '${{ env.TEST_ARTIFACT_VERSION }}-build'
       #   build: true
       #   publish: false

      - name: Test the action - only publish
        uses: ./
        with:
          api_key: '${{ secrets.GALAXY_API_KEY }}'
          collection_dir: 'fake_collection'
          # Should match version above
          galaxy_version: '${{ env.TEST_ARTIFACT_VERSION }}-build'
          build: true
          publish: true

 # snapshot:
 #   runs-on: ubuntu-latest
 #   steps:
 #     - uses: actions/checkout@v2.3.4

 #     - name: Set up Docker Buildx
 #       uses: docker/setup-buildx-action@v1.5.0

 #     - name: Login to GitHub Container Registry
 #       uses: docker/login-action@v1
 #       with:
 #         registry: ghcr.io
 #         username: ${{ github.actor }}
 #         password: ${{ secrets.GITHUB_TOKEN }}

 #    - name: Build and Push
 #       uses: docker/build-push-action@v2.6.1
 #       # uses: docker/build-push-action@v2.5.0
 #       with:
 #         context: .
 #         file: ./Dockerfile
 #         push: true
 #         tags: |
 #           ghcr.io/buluma/ansible_galaxy_collection-testartifact:SNAPSHOT-${{ github.sha }}
