on:
  release:
    types:
      - published
  workflow_dispatch:

env:
  IMAGE_NAME: buluma/ansible_galaxy_collection

name: Release
jobs:
  release:
    name: Release GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - name: Semver release
        uses: technote-space/release-github-actions@v8.0.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLEAN_TARGETS: ''

  # If on master branch, build and release image.
  release_to_galaxy:
    name: Release
    runs-on: ubuntu-latest
    needs: release
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v5
        with:
          context: .
          # attests: type=sbom,generator=image
          # provenance: mode=max
          # sbom: true
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: buluma/ansible_galaxy_collection:2.7.1, ${{ github.repository }}:latest
